
--用户表
DROP TABLE IF EXISTS `HM_USER`;
CREATE TABLE `HM_USER` (
  `USER_ID` bigint(25) NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(11) NOT NULL COMMENT '名字',
  `PASSWORD` varchar(255) NOT NULL,
  `USER_IMG` varchar(255) DEFAULT NULL COMMENT '用户头像',
  `GENDER` int(1) DEFAULT NULL,
  `ID_CARD` varchar(18) DEFAULT NULL,
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '用户创建时间',
  `MOBILE` varchar(20) DEFAULT NULL COMMENT '联系方式',
  `ADDRESS` varchar(255) DEFAULT NULL COMMENT '收货地址',
  `LAST_LOGIN_TIME` timestamp NULL DEFAULT NULL COMMENT '上次登录时间',
  `STORE_ID` bigint(25) DEFAULT NULL COMMENT '商家id ',  
  `IS_STORE` INTEGER(1) DEFAULT 0 COMMENT '是否是商家',
  `BUSSINESS_LICENSE` VARCHAR(255) DEFAULT NULL COMMENT '商家许可证 ',
  `STORE_ADDRESS` VARCHAR(255) DEFAULT NULL COMMENT '商家地址',
  `STORE_NAME` VARCHAR(255) DEFAULT NULL COMMENT '店名 ',
  `STORE_MOBILE` VARCHAR(255) DEFAULT NULL COMMENT '商家联系方式 ',
  `GETUI_CLIENT_ID` VARCHAR(100) DEFAULT NULL COMMENT '个推clientid',
  `DEVICE_INFO` VARCHAR(10) DEFAULT NULL COMMENT '客户端类型', -- e.g. : Andriod_Store
  
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



